name: pipe_tsm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytables
  - dask==2025.7.0
  - distributed==2025.7.0
  - dask-jobqueue==0.9.0
  - cdshealpix==0.7.2
  - lsdb==0.6.4
  - hats==0.6.4
  - pip:
      - PyYaml==6.0.2
      - tables_io==1.0.0
      - h5py==3.14.0
